### ISSUE TITLE
BUG: `ImportError: cannot import name 'MemoryDataSet' from 'kedro.io'` with Kedro 0.19

### ISSUE THREAD

**Issue by astrojuanlu** [neptune-ai/kedro-neptune#77]
### Describe the bug
As per title.

https://github.com/neptune-ai/kedro-neptune/blob/7fd9bb3b49c647ceb9b02f92ae9f2599ad77fce6/src/kedro_neptune/__init__.py#L36-L39

`*DataSet` variants were removed from Kedro 0.19 and kedro-datasets 2.0, only `*Dataset` (lowercase `s`) names remain.

**Comment by SiddhantSadangi** [comment]
Thanks for reporting this @astrojuanlu !

Will get this fixed in the next release ✅

**Comment by astrojuanlu** [comment]
Thanks! And sorry we could have been more upfront about this for plugin authors.

**Comment by SiddhantSadangi** [comment]
Hey @astrojuanlu 👋 

We just released [kedro-neptune 0.4.0](https://github.com/neptune-ai/kedro-neptune/releases/tag/0.4.0) which fixes this issue 🎉 

Thank you again for reporting this! 🙇

**Comment by astrojuanlu** [comment]
Thanks for the heads up!

**Comment by sebassaras02** [comment]
@astrojuanlu in the version 0.19.5 I am still having the issue 

`from kedro.io import MemoryDataSet`

How you were able to solve this?

**Comment by astrojuanlu** [comment]
@sebassaras02 yes, do `from kedro.io import MemoryDataset` (lowercase `s`)
